create styled template for main Activity screen with no data
redacademy/speakbox-fall-2018 pull request #52
Opened 2018-12-06 18:33 UTC by elim322

- Created a template with placeholders for images that will come from API. 
- Still waiting for fonts from designers therefore there are no fonts enabled. 
- Image background only works with percentages.

2018-12-06 19:01 UTC, siddharthparmar7 requested changes
Move all of your images into an images dir in your assets and no image should hang out by itself.

For the Activity screen, your margin/padding for the title of each activity seems off. Please take a look at the design and fix it.

Also, background for the activity screen is different in the design than your code. And each Activity has different width in design than your code. Please fix it.

Make the requested changes. Thank you.

2018-12-06 19:01 UTC, siddharthparmar7 commented on js/screens/Activity/ActivityContainer.js
>  import { View } from "react-native";
remove unnecessary imports.

2018-12-06 19:01 UTC, siddharthparmar7 commented on js/screens/Activity/styles.js
> +    height: "100%"
no %. Use Dimensions or flexbox or resize mode.

2018-12-06 19:01 UTC, siddharthparmar7 commented on js/screens/Activity/styles.js
> +    marginTop: 100
margin 100? remove it. Use Flexbox.

2018-12-06 19:01 UTC, siddharthparmar7 commented on js/screens/Activity/styles.js
> +    marginBottom: 125
same.

2018-12-07 23:25 UTC, 10thfloor approved these changes

2018-12-07 23:25 UTC, merged