add Loading Component with animation
redacademy/speakbox-fall-2018 pull request #85
Opened 2018-12-12 01:09 UTC by Juett

add Loading Component with animation

2018-12-13 17:39 UTC, siddharthparmar7 requested changes
Don't forget to squash your commits. Also, your feature branch should follow the conventions. Please make the requested changes. Thank you.

2018-12-13 17:39 UTC, siddharthparmar7 commented on js/components/ChooseAvatar/styles.js
> +    marginBottom: 15,
can you work without this huge margin?

2018-12-13 17:39 UTC, siddharthparmar7 commented on js/screens/Journal/Journal.js
>      <View>
use Fragment instead.

2018-12-13 17:39 UTC, siddharthparmar7 commented on js/components/Loading/Loading.js
> +} from "react-native";
please remove unnecessary imports.

2018-12-13 17:39 UTC, siddharthparmar7 commented on js/components/Loading/styles.js
> +import globalStyles from "../../config/styles";
remove unnecessary imports.

2018-12-14 19:51 UTC, Juett commented on js/components/ChooseAvatar/styles.js
> +    marginBottom: 15,
I tried everything I could not to use these huge margins but its the only way to match the design.

2018-12-14 23:55 UTC, siddharthparmar7 requested changes
your branch name is not correct. Use the conventions we showed you.

2018-12-15 00:35 UTC, closed without merging