Implement CrisisModal when CrisisButton is clicked
redacademy/speakbox-fall-2018 pull request #87
Opened 2018-12-13 18:32 UTC by ajaguasin

2018-12-13 19:41 UTC, siddharthparmar7 requested changes
Nice work. Please make the changes. Thank you.

2018-12-13 19:41 UTC, siddharthparmar7 commented on js/components/CrisisModal/CrisisModal.js
> +export default CrisisModal;
Add prop type validation, please.

2018-12-13 20:01 UTC, ajaguasin commented
Changes resolved, thank you

2018-12-14 18:43 UTC, siddharthparmar7 approved these changes
Nice work. Please make the changes in your next pull request.

2018-12-14 18:43 UTC, siddharthparmar7 commented on js/screens/CommunityQuestion/CommunityQuestion.js
>        </ScrollView>
you are receiving more props than just a navigation object. Please add prop type validation for all of your props.

2018-12-14 18:43 UTC, merged