create and style signup screen, add new user at signup
redacademy/speakbox-fall-2018 pull request #89
Opened 2018-12-14 17:43 UTC by juliabrowne

2018-12-14 20:04 UTC, siddharthparmar7 requested changes
Please make sure you file names and components are semantic. If you have a component SingUp, then you should have a component SignIn, not LogIn. Please make the changes. Thank you.

2018-12-14 20:04 UTC, siddharthparmar7 commented on js/components/SignupForm/SignupForm.js
> +    console.log(values)
remove all the console logs.

2018-12-14 20:04 UTC, siddharthparmar7 commented on js/App.js
>  import AppNavigator from "./navigation/RootStackNavigator";
remove all the unnecessary imports

2018-12-14 20:04 UTC, siddharthparmar7 commented on js/components/SignupForm/SignupForm.js
> +  Switch
remove all the unnecessary imports.

2018-12-14 20:04 UTC, siddharthparmar7 commented on js/components/SignupForm/SignupForm.js
> +      body: JSON.stringify(values)
const res is never used. Why?

2018-12-14 20:04 UTC, siddharthparmar7 commented on js/components/SignupForm/SignupForm.js
> +                        />
error state and validation for your form? Please validate your inputs.

2018-12-14 20:04 UTC, siddharthparmar7 commented on js/components/SignupForm/styles.js
> +  },
use prettier to format your code.

2018-12-14 20:04 UTC, siddharthparmar7 commented on js/screens/UserSignup/UserSignup.js
> +import styles from './styles'
remove all the unnecessary imports.

2018-12-14 20:04 UTC, siddharthparmar7 commented on js/screens/UserSignup/styles.js
> +const { width, height } = Dimensions.get('window')
remove unnecessary imports.

2018-12-14 21:08 UTC, juliabrowne commented on js/components/SignupForm/SignupForm.js
> +    console.log(values)
done!

2018-12-14 21:09 UTC, juliabrowne commented on js/components/SignupForm/SignupForm.js
> +  Switch
done!

2018-12-14 21:16 UTC, juliabrowne commented on js/components/SignupForm/SignupForm.js
> +                        />
done!

2018-12-14 21:16 UTC, juliabrowne commented on js/components/SignupForm/styles.js
> +  },
done!

2018-12-14 21:17 UTC, juliabrowne commented on js/screens/UserSignup/UserSignup.js
> +import styles from './styles'
done!

2018-12-14 21:17 UTC, juliabrowne commented on js/screens/UserSignup/styles.js
> +const { width, height } = Dimensions.get('window')
done!

2018-12-14 21:22 UTC, juliabrowne commented on js/components/SignupForm/SignupForm.js
> +      body: JSON.stringify(values)
it was originally there for a console log. i removed it!

2018-12-14 21:24 UTC, juliabrowne commented on js/App.js
>  import AppNavigator from "./navigation/RootStackNavigator";
done!

2018-12-17 17:15 UTC, siddharthparmar7 requested changes
Please make the changes. Thank you.

2018-12-17 17:15 UTC, siddharthparmar7 commented on js/components/SignupForm/SignupForm.js
> +                        />
I don't see it there. Please make the changes.

2018-12-17 17:15 UTC, siddharthparmar7 commented on js/components/SignupForm/SignupForm.js
> +                          style={{ fontFamily: 'Avenir' }}
show errors for all your text input.

2018-12-17 22:57 UTC, siddharthparmar7 approved these changes
Make the changes in your next pull request. And make sure all of your styles are in styles.js file from now on to get your pull request merged into the develop branch. Thank you.

2018-12-17 22:57 UTC, siddharthparmar7 commented on js/components/SignupForm/SignupForm.js
> +                          style={{ fontFamily: 'Avenir' }}
move all of your styles to styles.js file.

2018-12-17 22:57 UTC, siddharthparmar7 commented on js/components/SignupForm/SignupForm.js
> +                          style={{ fontFamily: 'Avenir' }}
move your styles to styles.js file.

2018-12-17 22:57 UTC, siddharthparmar7 commented on js/components/SignupForm/SignupForm.js
> +                          style={{ fontFamily: 'Avenir' }}
move your styles to styles.js

2018-12-17 22:57 UTC, siddharthparmar7 commented on js/components/SignupForm/SignupForm.js
> +                            style={{ fontFamily: 'Avenir' }}
move your styles to styles.js

2018-12-17 22:57 UTC, siddharthparmar7 commented on js/components/SignupForm/SignupForm.js
> +                            style={{ fontFamily: 'Avenir' }}
move your styles to styles.js

2018-12-17 22:57 UTC, merged